spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/STAR_WARS_PROJECT?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  #Cloudinary Properties
  cloudinary:
    api-key: 459979215534265
    api-secret: _wgmjJfOu9W3dACZwn4MD-5A4yI
    cloud-name: dedh1hh8k

  #Passwords for the first 2 users that are auto initialized in the DataBase: Admin and User
  STAR_WARS_PROJECT:
    admin:
      defaultPasswordForAdmin: test
    user:
      defaultPasswordForUser: test